import Hero from "../components/Hero";

export default function Landing1() {
  return (
    <>
      <Hero/>

      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse iaculis nunc tortor, in maximus odio rhoncus id. Proin eget feugiat nisi, id luctus magna. Phasellus tempus finibus mollis. Vivamus pretium neque et enim scelerisque, et efficitur augue gravida. Donec dapibus quam mauris, et ullamcorper felis ultrices at. Maecenas sodales imperdiet eros, vel mollis tellus pretium ac. Integer aliquam tortor eu velit accumsan, sit amet feugiat turpis porttitor. Etiam eros lacus, placerat at euismod ac, eleifend nec quam. Maecenas feugiat dui magna, at sollicitudin odio vehicula quis.

Sed sit amet enim vitae lectus bibendum ornare. Aliquam et commodo sem. Quisque ornare nisi ornare felis pellentesque, vitae dictum sapien vulputate. Suspendisse sagittis volutpat ornare. Proin non lobortis leo, a tristique mi. Aenean vestibulum efficitur nisi, sit amet vestibulum erat feugiat nec. Vestibulum nec neque commodo, vulputate justo non, dignissim ligula. Etiam metus libero, euismod mollis consectetur ac, ultrices commodo tellus. Nunc eget risus vehicula, lobortis ipsum sed, cursus diam. Fusce eleifend cursus velit ac feugiat. Morbi ornare facilisis tincidunt. Vivamus pulvinar dignissim scelerisque.

Quisque vitae tortor at magna dapibus iaculis sed id dolor. Nullam nunc arcu, rutrum id magna nec, tincidunt feugiat erat. Aenean in ex at turpis semper consequat id vitae velit. Maecenas sit amet lorem vitae magna fermentum convallis eget eget velit. Sed porttitor orci eu felis varius, in rhoncus ex blandit. Pellentesque sit amet felis nunc. In sit amet sapien convallis, suscipit erat ut, venenatis sapien. Proin maximus tempor eros, a porttitor nisl posuere ac. Etiam turpis neque, auctor ullamcorper nulla malesuada, placerat fermentum nibh. Mauris mattis leo quis lacus tempus, eget porta metus ultrices.

Fusce sagittis, arcu nec accumsan rhoncus, eros ligula tristique tortor, interdum fermentum lorem nisl sit amet velit. Praesent semper malesuada metus, nec mollis quam bibendum sed. Donec cursus suscipit finibus. Curabitur lobortis lorem id risus faucibus, et pharetra erat sagittis. Donec tristique nisi id ligula laoreet tempus. Aliquam vitae commodo augue, nec euismod quam. Aliquam id faucibus elit. Pellentesque sed lorem id diam pharetra ultrices. Donec sed magna mi. Morbi pharetra ligula non lacus dictum, vel efficitur turpis congue. Phasellus a felis consequat, dapibus mi eget, cursus justo. Nulla vel metus pretium, vulputate felis vel, vulputate dolor. Maecenas placerat augue felis, vitae elementum est ultrices dapibus. Fusce molestie dolor ut ultricies tempor. Aliquam pretium urna quis nibh porttitor, quis posuere erat condimentum.

Proin sit amet odio eget arcu scelerisque viverra laoreet at mauris. Nullam maximus pharetra sem, sit amet rutrum orci. Duis facilisis ex ut sapien sagittis, at convallis sem auctor. Ut laoreet, ante id sagittis ultrices, nibh ante rutrum arcu, sit amet ultricies nulla diam eget justo. Suspendisse urna libero, tempus a odio eu, pellentesque ornare massa. Praesent ullamcorper ligula maximus, posuere nibh non, bibendum neque. Vivamus posuere sodales ante vel gravida. Fusce vulputate suscipit magna, vel aliquam leo sagittis nec. Donec ornare elementum auctor. Etiam ante dui, porttitor sagittis placerat id, placerat at massa. Fusce pellentesque efficitur leo, et convallis nulla
      </div>

      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse iaculis nunc tortor, in maximus odio rhoncus id. Proin eget feugiat nisi, id luctus magna. Phasellus tempus finibus mollis. Vivamus pretium neque et enim scelerisque, et efficitur augue gravida. Donec dapibus quam mauris, et ullamcorper felis ultrices at. Maecenas sodales imperdiet eros, vel mollis tellus pretium ac. Integer aliquam tortor eu velit accumsan, sit amet feugiat turpis porttitor. Etiam eros lacus, placerat at euismod ac, eleifend nec quam. Maecenas feugiat dui magna, at sollicitudin odio vehicula quis.

Sed sit amet enim vitae lectus bibendum ornare. Aliquam et commodo sem. Quisque ornare nisi ornare felis pellentesque, vitae dictum sapien vulputate. Suspendisse sagittis volutpat ornare. Proin non lobortis leo, a tristique mi. Aenean vestibulum efficitur nisi, sit amet vestibulum erat feugiat nec. Vestibulum nec neque commodo, vulputate justo non, dignissim ligula. Etiam metus libero, euismod mollis consectetur ac, ultrices commodo tellus. Nunc eget risus vehicula, lobortis ipsum sed, cursus diam. Fusce eleifend cursus velit ac feugiat. Morbi ornare facilisis tincidunt. Vivamus pulvinar dignissim scelerisque.

Quisque vitae tortor at magna dapibus iaculis sed id dolor. Nullam nunc arcu, rutrum id magna nec, tincidunt feugiat erat. Aenean in ex at turpis semper consequat id vitae velit. Maecenas sit amet lorem vitae magna fermentum convallis eget eget velit. Sed porttitor orci eu felis varius, in rhoncus ex blandit. Pellentesque sit amet felis nunc. In sit amet sapien convallis, suscipit erat ut, venenatis sapien. Proin maximus tempor eros, a porttitor nisl posuere ac. Etiam turpis neque, auctor ullamcorper nulla malesuada, placerat fermentum nibh. Mauris mattis leo quis lacus tempus, eget porta metus ultrices.

Fusce sagittis, arcu nec accumsan rhoncus, eros ligula tristique tortor, interdum fermentum lorem nisl sit amet velit. Praesent semper malesuada metus, nec mollis quam bibendum sed. Donec cursus suscipit finibus. Curabitur lobortis lorem id risus faucibus, et pharetra erat sagittis. Donec tristique nisi id ligula laoreet tempus. Aliquam vitae commodo augue, nec euismod quam. Aliquam id faucibus elit. Pellentesque sed lorem id diam pharetra ultrices. Donec sed magna mi. Morbi pharetra ligula non lacus dictum, vel efficitur turpis congue. Phasellus a felis consequat, dapibus mi eget, cursus justo. Nulla vel metus pretium, vulputate felis vel, vulputate dolor. Maecenas placerat augue felis, vitae elementum est ultrices dapibus. Fusce molestie dolor ut ultricies tempor. Aliquam pretium urna quis nibh porttitor, quis posuere erat condimentum.

Proin sit amet odio eget arcu scelerisque viverra laoreet at mauris. Nullam maximus pharetra sem, sit amet rutrum orci. Duis facilisis ex ut sapien sagittis, at convallis sem auctor. Ut laoreet, ante id sagittis ultrices, nibh ante rutrum arcu, sit amet ultricies nulla diam eget justo. Suspendisse urna libero, tempus a odio eu, pellentesque ornare massa. Praesent ullamcorper ligula maximus, posuere nibh non, bibendum neque. Vivamus posuere sodales ante vel gravida. Fusce vulputate suscipit magna, vel aliquam leo sagittis nec. Donec ornare elementum auctor. Etiam ante dui, porttitor sagittis placerat id, placerat at massa. Fusce pellentesque efficitur leo, et convallis nulla
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse iaculis nunc tortor, in maximus odio rhoncus id. Proin eget feugiat nisi, id luctus magna. Phasellus tempus finibus mollis. Vivamus pretium neque et enim scelerisque, et efficitur augue gravida. Donec dapibus quam mauris, et ullamcorper felis ultrices at. Maecenas sodales imperdiet eros, vel mollis tellus pretium ac. Integer aliquam tortor eu velit accumsan, sit amet feugiat turpis porttitor. Etiam eros lacus, placerat at euismod ac, eleifend nec quam. Maecenas feugiat dui magna, at sollicitudin odio vehicula quis.

Sed sit amet enim vitae lectus bibendum ornare. Aliquam et commodo sem. Quisque ornare nisi ornare felis pellentesque, vitae dictum sapien vulputate. Suspendisse sagittis volutpat ornare. Proin non lobortis leo, a tristique mi. Aenean vestibulum efficitur nisi, sit amet vestibulum erat feugiat nec. Vestibulum nec neque commodo, vulputate justo non, dignissim ligula. Etiam metus libero, euismod mollis consectetur ac, ultrices commodo tellus. Nunc eget risus vehicula, lobortis ipsum sed, cursus diam. Fusce eleifend cursus velit ac feugiat. Morbi ornare facilisis tincidunt. Vivamus pulvinar dignissim scelerisque.

Quisque vitae tortor at magna dapibus iaculis sed id dolor. Nullam nunc arcu, rutrum id magna nec, tincidunt feugiat erat. Aenean in ex at turpis semper consequat id vitae velit. Maecenas sit amet lorem vitae magna fermentum convallis eget eget velit. Sed porttitor orci eu felis varius, in rhoncus ex blandit. Pellentesque sit amet felis nunc. In sit amet sapien convallis, suscipit erat ut, venenatis sapien. Proin maximus tempor eros, a porttitor nisl posuere ac. Etiam turpis neque, auctor ullamcorper nulla malesuada, placerat fermentum nibh. Mauris mattis leo quis lacus tempus, eget porta metus ultrices.

Fusce sagittis, arcu nec accumsan rhoncus, eros ligula tristique tortor, interdum fermentum lorem nisl sit amet velit. Praesent semper malesuada metus, nec mollis quam bibendum sed. Donec cursus suscipit finibus. Curabitur lobortis lorem id risus faucibus, et pharetra erat sagittis. Donec tristique nisi id ligula laoreet tempus. Aliquam vitae commodo augue, nec euismod quam. Aliquam id faucibus elit. Pellentesque sed lorem id diam pharetra ultrices. Donec sed magna mi. Morbi pharetra ligula non lacus dictum, vel efficitur turpis congue. Phasellus a felis consequat, dapibus mi eget, cursus justo. Nulla vel metus pretium, vulputate felis vel, vulputate dolor. Maecenas placerat augue felis, vitae elementum est ultrices dapibus. Fusce molestie dolor ut ultricies tempor. Aliquam pretium urna quis nibh porttitor, quis posuere erat condimentum.

Proin sit amet odio eget arcu scelerisque viverra laoreet at mauris. Nullam maximus pharetra sem, sit amet rutrum orci. Duis facilisis ex ut sapien sagittis, at convallis sem auctor. Ut laoreet, ante id sagittis ultrices, nibh ante rutrum arcu, sit amet ultricies nulla diam eget justo. Suspendisse urna libero, tempus a odio eu, pellentesque ornare massa. Praesent ullamcorper ligula maximus, posuere nibh non, bibendum neque. Vivamus posuere sodales ante vel gravida. Fusce vulputate suscipit magna, vel aliquam leo sagittis nec. Donec ornare elementum auctor. Etiam ante dui, porttitor sagittis placerat id, placerat at massa. Fusce pellentesque efficitur leo, et convallis nulla
      </div>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse iaculis nunc tortor, in maximus odio rhoncus id. Proin eget feugiat nisi, id luctus magna. Phasellus tempus finibus mollis. Vivamus pretium neque et enim scelerisque, et efficitur augue gravida. Donec dapibus quam mauris, et ullamcorper felis ultrices at. Maecenas sodales imperdiet eros, vel mollis tellus pretium ac. Integer aliquam tortor eu velit accumsan, sit amet feugiat turpis porttitor. Etiam eros lacus, placerat at euismod ac, eleifend nec quam. Maecenas feugiat dui magna, at sollicitudin odio vehicula quis.

Sed sit amet enim vitae lectus bibendum ornare. Aliquam et commodo sem. Quisque ornare nisi ornare felis pellentesque, vitae dictum sapien vulputate. Suspendisse sagittis volutpat ornare. Proin non lobortis leo, a tristique mi. Aenean vestibulum efficitur nisi, sit amet vestibulum erat feugiat nec. Vestibulum nec neque commodo, vulputate justo non, dignissim ligula. Etiam metus libero, euismod mollis consectetur ac, ultrices commodo tellus. Nunc eget risus vehicula, lobortis ipsum sed, cursus diam. Fusce eleifend cursus velit ac feugiat. Morbi ornare facilisis tincidunt. Vivamus pulvinar dignissim scelerisque.

Quisque vitae tortor at magna dapibus iaculis sed id dolor. Nullam nunc arcu, rutrum id magna nec, tincidunt feugiat erat. Aenean in ex at turpis semper consequat id vitae velit. Maecenas sit amet lorem vitae magna fermentum convallis eget eget velit. Sed porttitor orci eu felis varius, in rhoncus ex blandit. Pellentesque sit amet felis nunc. In sit amet sapien convallis, suscipit erat ut, venenatis sapien. Proin maximus tempor eros, a porttitor nisl posuere ac. Etiam turpis neque, auctor ullamcorper nulla malesuada, placerat fermentum nibh. Mauris mattis leo quis lacus tempus, eget porta metus ultrices.

Fusce sagittis, arcu nec accumsan rhoncus, eros ligula tristique tortor, interdum fermentum lorem nisl sit amet velit. Praesent semper malesuada metus, nec mollis quam bibendum sed. Donec cursus suscipit finibus. Curabitur lobortis lorem id risus faucibus, et pharetra erat sagittis. Donec tristique nisi id ligula laoreet tempus. Aliquam vitae commodo augue, nec euismod quam. Aliquam id faucibus elit. Pellentesque sed lorem id diam pharetra ultrices. Donec sed magna mi. Morbi pharetra ligula non lacus dictum, vel efficitur turpis congue. Phasellus a felis consequat, dapibus mi eget, cursus justo. Nulla vel metus pretium, vulputate felis vel, vulputate dolor. Maecenas placerat augue felis, vitae elementum est ultrices dapibus. Fusce molestie dolor ut ultricies tempor. Aliquam pretium urna quis nibh porttitor, quis posuere erat condimentum.

Proin sit amet odio eget arcu scelerisque viverra laoreet at mauris. Nullam maximus pharetra sem, sit amet rutrum orci. Duis facilisis ex ut sapien sagittis, at convallis sem auctor. Ut laoreet, ante id sagittis ultrices, nibh ante rutrum arcu, sit amet ultricies nulla diam eget justo. Suspendisse urna libero, tempus a odio eu, pellentesque ornare massa. Praesent ullamcorper ligula maximus, posuere nibh non, bibendum neque. Vivamus posuere sodales ante vel gravida. Fusce vulputate suscipit magna, vel aliquam leo sagittis nec. Donec ornare elementum auctor. Etiam ante dui, porttitor sagittis placerat id, placerat at massa. Fusce pellentesque efficitur leo, et convallis nulla
      </div>
    </>
  );
}
